airbnb_project_dbtsnowflake:
  outputs:
    dev:
      account: RLTSFME-SB79184
      database: AIRBNB
      password: Uk@utd08092001
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: UKANANI123
      warehouse: COMPUTE_WH
  target: dev
